import Head from 'next/head'
import P1 from '../components/P1'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Système Solaire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <P1 />
   
    </div>
  )
}
